dbmdz/digitalcollections-commons

dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/api/FileResourceRepository.java, dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImpl.java, dc-commons-file/src/main/java/de/digitalcollections/commons/file/business/api/FileResourceService.java, dc-commons-file/src/main/java/de/digitalcollections/commons/file/business/impl/service/FileResourceServiceImpl.java, dc-commons-file/src/test/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImplTest.java
With this PR the `write()` function (`FileResource`) now returns the number of written bytes (instead of `void`).
=> Fileresource: `write` returns written bytes

.travis.yml, dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml, dc-commons-prosemirror/pom.xml, dc-commons-springboot/src/main/java/de/digitalcollections/commons/springboot/metrics/MetricsService.java, dc-commons-springsecurity/pom.xml, pom.xml
This PR adds openjdk11 to Travis CI build matrix and introduces various fixes for openjdk11 :tada:
It also fixes code coverage calculation with `jacoco`.
=> Travis CI: OpenJDK 11

dc-commons-file/pom.xml, dc-commons-file/src/test/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImplTest.java, dc-commons-file/src/test/java/de/digitalcollections/core/backend/impl/file/repository/resource/resolver/MultiPatternsFileNameResolverImplTest.java, dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml, dc-commons-prosemirror/pom.xml, dc-commons-server/pom.xml, dc-commons-server/src/test/java/de/digitalcollections/commons/server/HttpLoggingUtilitiesTest.java, dc-commons-springboot/pom.xml, dc-commons-springmvc/pom.xml, dc-commons-springmvc/src/test/java/de/digitalcollections/commons/springmvc/interceptors/CurrentUrlAsModelAttributeHandlerInterceptorTest.java, dc-commons-springsecurity/pom.xml, dc-commons-validation/pom.xml, dc-commons-validation/src/test/java/de/digitalcollections/commons/validation/StringAssertionsTest.java, dc-commons-xml/pom.xml, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathExpressionCacheTest.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathWrapperTest.java, dc-commons-yaml/pom.xml, dc-commons-yaml/src/test/java/de/digitalcollections/commons/yaml/StringRepresentationsTest.java, dc-commons-yaml/src/test/java/de/digitalcollections/commons/yaml/YamlTest.java, dc-commons-yaml/src/test/java/de/digitalcollections/commons/yaml/examples/BenchmarkTest.java, pom.xml
This PR migrates old JUnit4 tests to JUnit5.
**Notes**:
The `TemporaryFolder` class no longer exists in JUnit5. We could use an extra plugin like `junit-pioneer` to get the same functionality as in JUnit4. An example of  using `TemporaryFolder` with `junit-pioneer` is shown in [this pull request](https://github.com/junit-pioneer/junit-pioneer/commit/efaf553d1d08537b1a0bf789298aa939444e4026). The removal of test cases that used `TemporaryFolder` caused the code coverage dropdown.
=> WIP: Test cases: Migrate to JUnit5

dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathWrapper.java
Empty nodes are a common use case, so there's no need to log them out. 
Those, who really need information about it, can use the debug log lovel now.
=> Turned misleading logging info stmt into a debug stmt

dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml, pom.xml
This PR updates the version of `jackson` to fix CVE-2018-19360, CVE-2018-19362 and CVE-2018-19361.
This was found during a GitHub Security Scan.
=> Security alert: update version of jackson

dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/resolver/MultiPatternsFileNameResolverImpl.java, dc-commons-file/src/main/java/de/digitalcollections/commons/file/business/impl/service/FileResourceServiceImpl.java, dc-commons-file/src/test/java/de/digitalcollections/commons/file/backend/impl/resolver/MultiPatternsFileNameResolverImplTest.java
Dependency injection via attributes is discouraged because it makes testing more complicated and often produces an overall higher complexity.
=> Refactor code to use constructor injection

dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/resolved/ResolvedFileResourceRepositoryImpl.java
needed to avoid spring circular references
=> Add method for adding resolvers without autowiring

dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/UniversalNamespaceContext.java, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathExpressionCache.java, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathWrapper.java
The `DigitalCollectionsNamespaceContext` remains the default, but you can now opt to use a custom `NamespaceContext` instance.
Included is a `UniversalNamespaceContext` that allows setting user-defined `(prefix, uri)` mappings, but falls back to the namespace prefixes declared in the document's root element.
=> xml: Add universal namespace resolver to simplify working with namespaced XML

dc-commons-springmvc/pom.xml
This PR upgrades some libraries in the submodule `dc-commons-springmvc` to their latest version.
=> Bump dependencies to their latest version

dc-commons-server/pom.xml, dc-commons-springboot/pom.xml, dc-commons-springsecurity/pom.xml
Hi,
this PR removes `hamcrest-core` as (test) dependency for maintainability reasons, as it is not needed.
=> tree-wide pom: remove hamcrest-core

dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathBinding.java, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathMapper.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java
To be able to evaluate XPath expressions without using a template, the XPathBinding annotation was modifed to use a new field, `expressions`. Because of that, the field `variables` had to be made optional. It is guaranteed, that never both fields are used at the same time.
The XPathMapper is able to evaluate the new field `expressions` and return the results directly without a value template.
=> Extend xpathmapper to be able to work without templates

dc-commons-xml/pom.xml, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathBinding.java, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathMapper.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java, dc-commons-xml/src/test/resources/bsbstruc.xml
This PR implements the ability to return `List<String>` for multivalued fields (plain fields and multi language fields) for expressions, but not in templates.
=> Ability to return multivalued fields in expressions

dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/UniversalNamespaceContext.java, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathBinding.java, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathMapper.java, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathRoot.java, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathVariable.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java
This PR introduces the @XPathRoot annotation as Type level, which allows not only shorter @XPathBindings on the methods, but also prepares an API for later caching of subtrees.
Example usage:
```java
@XPathRoot(
defaultNamespace = "http://www.tei-c.org/ns/1.0",
value = { "/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:listBibl/tei:biblStruct" }
)
private interface XPathRootMapper {
@XPathBinding(
expressions = { "/tei:monogr/tei:author/tei:persName/tei:name"}
)
String getAuthor() throws XPathMappingException;
}
=> Introducing @XPathRoot annotation for brevity

dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/DocumentReader.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/DocumentReaderTest.java
This PR allows handling of unknown languages, e.g. `und`
=> Fix for unknown languages

dc-commons-jdbi/src/main/java/de/digitalcollections/commons/jdbi/DcCommonsJdbiPlugin.java, dc-commons-jdbi/src/main/java/de/digitalcollections/commons/jdbi/LocaleArgumentFactory.java, dc-commons-jdbi/src/main/java/de/digitalcollections/commons/jdbi/LocaleColumnMapperFactory.java
Add locale/language data type (storing into VARCHAR) as postgres has no Locale-Datatype.
Needed e.g. to be able to save language of an item.
=> Add locale/language data type (storing into VARCHAR)

dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathMapper.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java, dc-commons-xml/src/test/resources/nested-multi.xml
If a field or setter is annotated with `@XPathRoot` and its type is `List<T>`, where `T` is a type with mapping annotations of its own, the `XPathMapper` will now create instances of `T` from every element matching the paths in `XPathRoot`, using the sub-tree (with the matching
element as the root) for the mapping.
As an example, given the following XML:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<outer>
<author>
<id>1337</id>
<name>Chuck Norris</name>
</author>
<author>
<id>42</id>
<name>Frank Zappa</name>
</author>
<character>
<id>1970</id>
<name>Bobby Brown</name>
</character>
</outer>
```
these two mapping classes provide identical functionality:
```java
public static class MultiNestedInnerRoot {
@XPathRoot({"/outer/author", "/outer/character"})
public List<Person> persons;
public …
```
=> Add support for mapping List<T> of nested types

dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathMapper.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java
These types would fail mapping after the last changeset.
=> Fix handling of nested types with no root paths

dc-commons-xml/pom.xml, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/DocumentReader.java
Für Nodes ohne Locale kann die Geschwindigkeit der Auswertung massiv gesteigert werden, wenn man deren Values in einer getrennten Liste vorhält.
=> Speedup for empty locale

dc-commons-xml/pom.xml, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/DocumentReader.java, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathWrapper.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java, dc-commons-xml/src/test/resources/bsbstruc.xml
Für reine String-Rückgaben bzw. Rückgaben einer Liste von Strings wird nicht mehr der Sonderweg über die Lokalisierung eingeschlagen. Außerdem wird intern nicht mehr davon ausgegangen, dass die XPath-Evaluierung eine NodeList zurückgibt, sondern sie kann auch Strings, Numbers und Booleans zurückgeben, wobei die letzten beiden ignorieren können, da wir ausschließlich Strings als Rückgabe erlauben.
=> Non-localized results no longer bound to Node lists (fixes #289)

dc-commons-xml/pom.xml, dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathMapper.java, dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java
This PR extends the XPathMapping to return boolean values, too.
This can be used to evaluate expressions like `count(/foo/bar)>0`.
=> Ability to return boolean values

dc-commons-file/pom.xml, dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/FileSystemResourceIOException.java, dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/api/FileResourceRepository.java, dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImpl.java
...to differentiate between "no readable resources found for identifier" and "potential resource found, but I/O error prevented us from completing the operation".
We want to differentiate downstream between the two (e.g. in a webservice the former would be a 404 and the latter a 500, raw disk i/o is definitely an internal server error).
We opted for subclassing the existing `ResourceIOException` as to not break the existing API.
=> commons-file: Add new FileSystemResourceIOException

dc-commons-springmvc/CHANGELOG.md, dc-commons-springmvc/pom.xml, dc-commons-springmvc/src/main/java/de/digitalcollections/commons/springmvc/converter/StringToOrderConverter.java
- Refactorings to use `dc-model` in version 10 with inner class builders
=> Refactorings for using refactored builder patterns from dc-model

dc-commons-springmvc/CHANGELOG.md, dc-commons-springmvc/pom.xml, dc-commons-springmvc/src/main/java/de/digitalcollections/commons/springmvc/converter/StringToOrderConverter.java, dc-commons-springmvc/src/test/java/de/digitalcollections/commons/springmvc/converter/StringToOrderConverterTest.java
StringToOrderConverter now allows subProperty containing dash "-" (e.g. "label=de-Latn")
=> Fix dash in subproperty

dc-commons-file/pom.xml, dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/api/IdentifierToFileResourceUriResolver.java, dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/IdentifierPatternToFileResourceUriResolverImpl.java
Hi,
this PR adjusts the `getUris` method and checks the correct return type (`MIME_APPLICATION_OCTET_STREAM` instead of `null`), because this is necessary due to changes introduced in `dc-model`:
https://github.com/dbmdz/digitalcollections-model/commit/331ba13afdadd3da03fc99ac03190eb88d7e84d0
=> Fix getUris check

dc-commons-file/CHANGELOG.md
Hi,
this PR extends changelog of dc-commons-file and mentions latest 6.0.1 release.
=> changelog: add entry for latest 6.0.1 release
