dbmdz/digitalcollections-commons

dc-commons-file/pom.xml
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/api/FileResourceRepository.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImpl.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/handler/ManagedResourcePersistenceTypeHandler.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/business/api/FileResourceService.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/business/impl/service/FileResourceServiceImpl.java
dc-commons-file/src/test/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImplTest.java
dc-commons-jdbi/pom.xml
dc-commons-jdbi/src/main/java/de/digitalcollections/commons/jdbi/DcCommonsJdbiPlugin.java
dc-commons-jdbi/src/main/java/de/digitalcollections/commons/jdbi/MimeTypeArgumentFactory.java
dc-commons-jdbi/src/main/java/de/digitalcollections/commons/jdbi/MimeTypeColumnMapperFactory.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/OrderConverter.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/PageableConverter.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/SortConverter.java
dc-commons-springmvc/src/main/resources/de/digitalcollections/commons/springmvc/thymeleaf/templates/fragments/pagination-navigation.html
dc-commons-springmvc/src/main/resources/messages-commons_de.properties
dc-commons-springmvc/src/main/resources/messages-commons_en.properties
pom.xml

Change FileResource handling for file uploads

Resource handling

---

dc-commons-feign/pom.xml
dc-commons-file/pom.xml
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImpl.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/resolver/FileNameResolver.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/resolver/MultiPatternsFileNameResolverImpl.java
dc-commons-jdbi/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model/pom.xml
dc-commons-prosemirror/pom.xml
dc-commons-server/pom.xml
dc-commons-springaop/pom.xml
dc-commons-springboot/pom.xml
dc-commons-springdata/pom.xml
dc-commons-springmvc/pom.xml
dc-commons-springsecurity/pom.xml
dc-commons-validation/pom.xml
dc-commons-xml/pom.xml
dc-commons-yaml/pom.xml
pom.xml

Also fixes dependency security issue

Fixes and upgrades

---

dc-commons-feign/pom.xml
dc-commons-file/pom.xml
dc-commons-jdbi/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml
dc-commons-springboot/pom.xml
dc-commons-validation/pom.xml
dc-commons-yaml/pom.xml
pom.xml

cleanup order and version management in several pom.xml files

pom.xml cleanup

---

dc-commons-feign/pom.xml
dc-commons-file/pom.xml
dc-commons-jdbi/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model/pom.xml
dc-commons-prosemirror/pom.xml
dc-commons-server/pom.xml
dc-commons-springaop/pom.xml
dc-commons-springboot/pom.xml
dc-commons-springdata/pom.xml
dc-commons-springmvc/pom.xml
dc-commons-springsecurity/pom.xml
dc-commons-validation/pom.xml
dc-commons-xml/pom.xml
dc-commons-yaml/pom.xml
pom.xml

First release candidate for upcoming 2.1.0 release 🎉

Version 2.1.0.RC1

---

dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/api/FileResourceRepository.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImpl.java
dc-commons-file/src/test/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImplTest.java

This PR fixes problems with generics.

Fix problems with generics

---

dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/handler/ManagedResourcePersistenceTypeHandler.java

no extension appended in null case

Fix nullpointer if mimetype has no extension

---

dc-commons-file/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml
dc-commons-prosemirror/pom.xml
dc-commons-server/pom.xml
dc-commons-springboot/pom.xml
dc-commons-springboot/src/test/java/de/digitalcollections/commons/springboot/contributor/VersionInfoContributorTest.java
dc-commons-springboot/src/test/java/de/digitalcollections/commons/springboot/monitoring/VersionInfoTest.java
dc-commons-springmvc/pom.xml
dc-commons-springsecurity/pom.xml
dc-commons-validation/pom.xml
dc-commons-xml/pom.xml
dc-commons-yaml/pom.xml
pom.xml

includes all other 10 version upgrades

Upgrade libraries mentioned by dependabot

---

dc-commons-feign/pom.xml
dc-commons-file/pom.xml
dc-commons-jdbi/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model/pom.xml
dc-commons-prosemirror/pom.xml
dc-commons-server/pom.xml
dc-commons-springaop/pom.xml
dc-commons-springboot/pom.xml
dc-commons-springdata/pom.xml
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/PageableConverter.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/SortConverter.java
dc-commons-springmvc/pom.xml
dc-commons-springsecurity/pom.xml
dc-commons-validation/pom.xml
dc-commons-xml/pom.xml
dc-commons-yaml/pom.xml
pom.xml

Reorganize modules. Make each module separately releasable (with own version)

Splitted libraries

---

dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/api/FileResourceRepository.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImpl.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/business/api/FileResourceService.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/business/impl/FileResourceServiceImpl.java
nbactions.xml

Add mimetype specific instantiation of subclasses of fileresource to repository implementation.

Typed fileresource handling

---

dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/managed/ManagedFileResourceRepositoryImpl.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/resolved/ResolvedFileResourceRepositoryImpl.java

needed to return mimetype specific fileresource implementations and fixing uri for filenames containing spaces

Fix fileresource creation by mimetype

---

dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/managed/ManagedFileResourceRepositoryImpl.java
dc-commons-file/src/test/java/de/digitalcollections/commons/file/backend/impl/managed/ManagedFileResourceRepositoryImplTest.java

Remove filename from managed fileresources on disk

---

dc-commons-file/README.md
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/api/FileResourceRepository.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImpl.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/business/api/FileResourceService.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/business/impl/FileResourceServiceImpl.java

Add create and remove write

---

dc-commons-file/README.md
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImpl.java
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/IdentifierPatternToFileResourceUriResolvingUtil.java
dc-commons-file/src/test/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImplTest.java

Added resolving of wildcard filenames in pattern configuration, e.g. *.xml (for mimetype xml) or * (for wildcard mimetype)

Wildcard filenames

---

dc-commons-jdbi/src/main/java/de/digitalcollections/commons/jdbi/MimeTypeColumnMapperFactory.java

return null if typename in database is null

Add null check in reading mimetype from database

---

dc-commons-jdbi/pom.xml

already tested in cudami, working

Bump version of jdbi to 3.12.0

---

dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/DocumentReader.java
dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathMapper.java
dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java

This MR adds the ability to return an ordered element list for further processing on the consumer side

Ability to return an ordered element list for further processing

---

dc-commons-feign/pom.xml
dc-commons-file/pom.xml
dc-commons-file/src/main/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImpl.java
dc-commons-jdbi/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml
dc-commons-server/pom.xml
dc-commons-springaop/pom.xml
dc-commons-springboot/pom.xml
dc-commons-springdata/pom.xml
dc-commons-springmvc/pom.xml
dc-commons-springsecurity/pom.xml
dc-commons-validation/pom.xml
dc-commons-xml/pom.xml
dc-commons-yaml/pom.xml
pom.xml

a bulk version upgrade of all dependabot suggestions in the other pull requests

Upgrade versions

---

dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/XPathMapper.java
dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperFixture.java

Add convenience methods to XPathMapper for reading document from path or inputstream

Add loading of xmlfile

---

dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/PageableConverter.java

Wihtout sorting another constructor has to be called

Fix NPE in PageableConverter

---

dc-commons-file/pom.xml
dc-commons-jdbi/pom.xml
dc-commons-prosemirror/dc-commons-prosemirror-model-jackson/pom.xml
dc-commons-springboot/pom.xml
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/PageableConverter.java
dc-commons-springmvc/pom.xml
dc-commons-springsecurity/pom.xml
dc-commons-yaml/pom.xml

Bump version of dependabot updates

Upgrade libraries

---

dc-commons-file/src/test/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImplTest.java

Use new junit temporary directory environment (OS independent)

---

dc-commons-feign/pom.xml
dc-commons-file/pom.xml
dc-commons-file/src/test/java/de/digitalcollections/commons/file/backend/impl/FileResourceRepositoryImplTest.java
dc-commons-jdbi/pom.xml
dc-commons-springdata/pom.xml

Bump version of dc-model to 6.1.0 and spring-data-commons to 2.2.7.RELEASE

Upgrade dependencies

---

dc-commons-xml/pom.xml
dc-commons-xml/src/main/java/de/digitalcollections/commons/xml/xpath/DocumentReader.java
dc-commons-xml/src/test/java/de/digitalcollections/commons/xml/xpath/XPathMapperTest.java
dc-commons-xml/src/test/resources/bsb10000001_page.xml

Empty locale of variables in template causes duplication as empty language is recognized as independent language for itself.
Now skipping empty language as long there is another language for the template

Fix duplicate values for undefined locales

---

dc-commons-jdbi/pom.xml
dc-commons-jdbi/src/main/java/de/digitalcollections/commons/jdbi/MimeTypeArgumentFactory.java
dc-commons-jdbi/src/main/java/de/digitalcollections/commons/jdbi/MimeTypeColumnMapperFactory.java
dc-commons-springdata/pom.xml
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/OrderConverter.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/PageConverter.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/PageableConverter.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/SortConverter.java

* package for mimetype changed
* depends on dc-model 9.0.0-SNAPSHOT

Bump version of dc-model to 9.0.0-SNAPSHOT

---

dc-commons-springmvc/CHANGELOG.md
dc-commons-springmvc/pom.xml
dc-commons-springmvc/src/main/java/de/digitalcollections/commons/springmvc/converter/StringToOrderConverter.java
dc-commons-springmvc/src/test/java/de/digitalcollections/commons/springmvc/converter/StringToOrderConverterTest.java

This PR adds a Spring converter that converts instances of String to ones of Order.

Order converter

---

dc-commons-springmvc/src/main/java/de/digitalcollections/commons/springmvc/converter/StringToOrderConverter.java
dc-commons-springmvc/src/test/java/de/digitalcollections/commons/springmvc/converter/StringToOrderConverterTest.java

* Changes for using dc-model version 10

Changes for model 10

---

dc-commons-springdata/pom.xml
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/OrderConverter.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/PageConverter.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/PageableConverter.java
dc-commons-springdata/src/main/java/de/digitalcollections/commons/springdata/domain/SortConverter.java

new model 10 pagerequest and pageresponse

Migrate to model version 10
